CREATE TABLE usuarios (
  id_usuario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(100) NOT NULL,
  password BLOB NOT NULL,
  UNIQUE KEY EMAIL_UNIQUE (email),
  PRIMARY KEY(id_usuario)
)ENGINE = InnoDB;


CREATE TABLE documentos (
  id_documento INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  id_usuario INTEGER UNSIGNED NOT NULL,
  url VARCHAR(100) NOT NULL,
  descripcion VARCHAR(500),
  PRIMARY KEY(id_documento)
)ENGINE = InnoDB;

ALTER TABLE documentos ADD CONSTRAINT FK_DOCUMENTOS_USUARIOS FOREIGN KEY FK_DOCUMENTOS_USUARIOS (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE;