/*
 * SeleniumTest.java
 * JUnit based test
 *
 * Created on 15 de mayo de 2007, 20:29
 */

package seleniumtest;

import junit.framework.*;

/**
 *
 * @author Juanjito
 */
public class SeleniumTest extends TestCase {
    
    public SeleniumTest(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("SeleniumTest");
        suite.addTest(IndexUserNoValidES.suite());
        suite.addTest(IndexUserNoValidEN.suite());
        suite.addTest(IndexUserValidES.suite());
        suite.addTest(IndexUserValidES.suite());
        suite.addTest(IndexUserNoValidFR.suite());
        suite.addTest(IndexUserValidFR.suite());
        
        suite.addTest(ChangeColor.suite());
        suite.addTest(ChangePage1_2EN.suite());
        suite.addTest(ChangePage1_2ES.suite());
        suite.addTest(HelpLookEN.suite());
        suite.addTest(HelpLookES.suite());
        suite.addTest(HelpUpEN.suite());
        suite.addTest(HelpUpES.suite());
        suite.addTest(InvitationES.suite());
        suite.addTest(InvitationEN.suite());
        suite.addTest(LookFileNoValidEN.suite());
        suite.addTest(LookFileNoValidES.suite());
        suite.addTest(LookFileValidEN.suite());
        suite.addTest(LookFileValidES.suite());
        
        suite.addTest(LinkFileEN.suite());
        suite.addTest(LinkFileES.suite());
        
        suite.addTest(ChangePage2_3ES.suite());
        suite.addTest(ChangePage2_3EN.suite());
        
        suite.addTest(NewFolderEN.suite());
        suite.addTest(NewFolderES.suite());
        
        suite.addTest(RenameFolderEN.suite());
        suite.addTest(RenameFolderES.suite());
        
        
        
        return suite;
    }
    
}
